version: "3.4"

services:
  vocexplorer:
    image: "vocdoni/vocexplorer:latest"
    build:
      context: ../..
    ports:
      - "26656:26656"      
      - "9090:9090"
      - "9091:9091"
      - "4001:4001"
      - "4171:4171"
      - "5001:5001"
      - "9096:9096"
      - "8081:8081"
    env_file: env
    volumes:
      - "vocexplorer:/data/vocexplorer"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

volumes:
  vocexplorer: {}
