version: "3.4"

services:
  explorer:
    image: "vocdoni/vocexplorer:${EXPLORER_TAG}"
    build:
      context: ../..
    env_file: .env
    volumes:
      - "vocexplorer:/data/vocexplorer"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.explorer.entrypoints=websecure"
      - "traefik.http.routers.explorer.tls.certresolver=le"
      - "traefik.http.routers.explorer.service=explorer"
      - "traefik.http.routers.explorer.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.explorer.loadbalancer.server.port=8081"
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

  gateway:
    image: "vocdoni/go-dvote:${GATEWAY_TAG}"
    env_file: .env
    volumes:
    - "run:/app/run"
    ports:
      # - "9090:9090"
      - "9091:9091"
      - "4001:4001"
      - "4171:4171"
      - "5001:5001"
      - "9096:9096"
      - "26656:26656"
      - "26657:26657"
      - "61000-61100:61000-61100"
    sysctls:
      net.core.somaxconn: 8128
    restart: ${RESTART:-no}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls.certresolver=le"
      - "traefik.http.routers.gateway.service=gateway"
      - "traefik.http.routers.gateway.rule=(Host(`${DOMAIN}`) && PathPrefix(`/dvote`))"
      - "traefik.http.services.gateway.loadbalancer.server.port=9090"
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

  traefik:
    image: traefik:2.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        #- /root/.docker/config.json:/config.json
      - /home/vocdoni/.docker/config.json:/config.json
    labels:
      - com.centurylinklabs.watchtower.enable="false"
    command: --interval 30 --cleanup


volumes:
  vocexplorer: {}
  run: {}

